services:
    locality_app:
        image: locality_app:latest
        container_name: locality_app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        env_file:
            - .env
        networks:
            - locality_network
        deploy:
            resources:
                limits:
                    cpus: "1.0"
                    memory: "1G"

networks:
    locality_network:
        external: true
